#!/usr/bin/env bash
# RouteLag MVP — install WireGuard server on Ubuntu 24.04.
# Safe to re-run; skips config regeneration if wg0 is already active.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

require_root

FORCE_REGEN=false
if [[ "${1:-}" == "--force" ]]; then
    FORCE_REGEN=true
fi

safe_echo "INFO" "Starting RouteLag MVP server installation..."

# --- Install packages ---
print_section "Installing Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y \
    wireguard \
    wireguard-tools \
    ufw \
    curl \
    nano \
    htop \
    traceroute \
    mtr-tiny \
    iperf3

safe_echo "INFO" "Packages installed."

# --- Detect default interface ---
DEFAULT_IFACE="$(detect_default_interface)"
safe_echo "INFO" "Default network interface: ${DEFAULT_IFACE}"

# --- Generate server keys if missing ---
print_section "Server Keys"
mkdir -p "${WG_KEYS_DIR}"
chmod 700 "${WG_KEYS_DIR}"

if [[ -f "${SERVER_PRIVATE_KEY}" && -f "${SERVER_PUBLIC_KEY}" ]]; then
    safe_echo "INFO" "Server keys already exist — skipping generation."
else
    safe_echo "INFO" "Generating new server key pair..."
    umask 077
    wg genkey | tee "${SERVER_PRIVATE_KEY}" | wg pubkey > "${SERVER_PUBLIC_KEY}"
    chmod 600 "${SERVER_PRIVATE_KEY}"
    chmod 644 "${SERVER_PUBLIC_KEY}"
    safe_echo "INFO" "Server keys created."
fi

SERVER_PRIV="$(cat "${SERVER_PRIVATE_KEY}")"
SERVER_PUB="$(cat "${SERVER_PUBLIC_KEY}")"

# --- Create WireGuard config ---
print_section "WireGuard Configuration"

SKIP_CONFIG=false
if [[ -f "${WG_CONF}" ]]; then
    if systemctl is-active --quiet "wg-quick@${WG_INTERFACE}" 2>/dev/null && [[ "${FORCE_REGEN}" == "false" ]]; then
        safe_echo "INFO" "wg0 is active and config exists — skipping config regeneration."
        safe_echo "INFO" "Use --force to regenerate config (existing peers will be lost)."
        SKIP_CONFIG=true
    else
        backup_file "${WG_CONF}"
    fi
fi

if [[ "${SKIP_CONFIG}" == "false" ]]; then
    # Preserve existing [Peer] blocks when re-running without --force on stopped service
    PEERS_BLOCK=""
    if [[ -f "${WG_CONF}" && "${FORCE_REGEN}" == "false" ]]; then
        PEERS_BLOCK="$(awk '/^\[Peer\]/{found=1} found{print}' "${WG_CONF}" || true)"
    fi

    cat > "${WG_CONF}" <<EOF
# RouteLag MVP — WireGuard server config
# Generated by 01-install-server.sh

[Interface]
Address = ${SERVER_TUNNEL_IP}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIV}
SaveConfig = false

PostUp = iptables -A FORWARD -i %i -o ${DEFAULT_IFACE} -j ACCEPT; iptables -A FORWARD -i ${DEFAULT_IFACE} -o %i -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -A POSTROUTING -s ${WG_SUBNET} -o ${DEFAULT_IFACE} -j MASQUERADE; iptables -t mangle -A FORWARD -o %i -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
PostDown = iptables -D FORWARD -i %i -o ${DEFAULT_IFACE} -j ACCEPT; iptables -D FORWARD -i ${DEFAULT_IFACE} -o %i -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -D POSTROUTING -s ${WG_SUBNET} -o ${DEFAULT_IFACE} -j MASQUERADE; iptables -t mangle -D FORWARD -o %i -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
EOF

    if [[ -n "${PEERS_BLOCK}" ]]; then
        echo "" >> "${WG_CONF}"
        echo "${PEERS_BLOCK}" >> "${WG_CONF}"
        safe_echo "INFO" "Preserved existing peer entries."
    fi

    chmod 600 "${WG_CONF}"
    safe_echo "INFO" "Created ${WG_CONF}"
fi

# --- Enable IPv4 forwarding ---
print_section "IP Forwarding"
cat > "${FORWARDING_CONF}" <<EOF
# RouteLag — forwarding + loose rp_filter for NAT routing
net.ipv4.ip_forward=1
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.default.rp_filter=2
EOF
sysctl -p "${FORWARDING_CONF}" >/dev/null
safe_echo "INFO" "IPv4 forwarding and loose rp_filter enabled."

# --- Configure UFW safely ---
print_section "Firewall (UFW)"

# Always allow SSH first — never lock ourselves out.
ufw allow OpenSSH comment 'SSH access' >/dev/null 2>&1 || ufw allow 22/tcp comment 'SSH access'
safe_echo "INFO" "SSH (port 22) allowed."

ufw allow "${WG_PORT}/udp" comment 'WireGuard' >/dev/null 2>&1 || true
safe_echo "INFO" "WireGuard (UDP ${WG_PORT}) allowed."

# Do not open high game ports inbound. Block legacy unsafe agent ports.
ufw deny 3000/tcp comment 'Block legacy VPS agent' >/dev/null 2>&1 || true
ufw deny 9999/udp comment 'Block legacy UDP logger' >/dev/null 2>&1 || true

UFW_STATUS="$(ufw status 2>/dev/null | head -1 || echo 'inactive')"
if echo "${UFW_STATUS}" | grep -qi inactive; then
    safe_echo "INFO" "Enabling UFW..."
    ufw --force enable
else
    safe_echo "INFO" "UFW is already active."
fi

# --- Enable and start WireGuard ---
print_section "Starting WireGuard"
systemctl enable "wg-quick@${WG_INTERFACE}"
systemctl restart "wg-quick@${WG_INTERFACE}"

# Brief wait for interface to come up
sleep 1

if systemctl is-active --quiet "wg-quick@${WG_INTERFACE}"; then
    safe_echo "INFO" "wg-quick@${WG_INTERFACE} is active."
else
    safe_echo "ERROR" "wg-quick@${WG_INTERFACE} failed to start."
    journalctl -u "wg-quick@${WG_INTERFACE}" -n 20 --no-pager || true
    exit 1
fi

# --- Final output ---
print_section "Installation Complete"
PUBLIC_IP="$(get_public_ip || true)"

echo ""
echo "  Server Public Key: ${SERVER_PUB}"
echo "  Endpoint:          ${PUBLIC_IP}:${WG_PORT}"
echo "  Tunnel subnet:     ${WG_SUBNET}"
echo "  Server tunnel IP:  ${SERVER_TUNNEL_IP}"
echo ""
echo "  Next steps:"
echo "    1. Ensure UDP ${WG_PORT} is open in your VPS provider panel (Maxko)."
echo "    2. Run: sudo ./scripts/02-create-client.sh <client-name>"
echo "    3. Copy the client config to your PC and import into WireGuard."
echo ""

print_section "WireGuard Status"
wg show "${WG_INTERFACE}" || safe_echo "WARN" "Could not show WireGuard status."

safe_echo "INFO" "Server installation finished successfully."
