#!/usr/bin/env bash
# RouteLag — install WireGuard on a routing node VPS.
# Override tunnel subnet via env before running:
#   ROUTELAG_WG_SUBNET=10.68.0.0/24 ROUTELAG_SERVER_TUNNEL_IP=10.68.0.1/24 sudo ./scripts/01-install-node.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

require_root

FORCE_REGEN=false
if [[ "${1:-}" == "--force" ]]; then
    FORCE_REGEN=true
fi

safe_echo "INFO" "Starting RouteLag node installation (subnet ${WG_SUBNET})..."

print_section "Installing Packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y \
    wireguard \
    wireguard-tools \
    ufw \
    curl \
    nano \
    htop \
    traceroute \
    mtr-tiny \
    iperf3

DEFAULT_IFACE="$(detect_default_interface)"
safe_echo "INFO" "Default network interface: ${DEFAULT_IFACE}"

print_section "Server Keys"
mkdir -p "${WG_KEYS_DIR}"
chmod 700 "${WG_KEYS_DIR}"

if [[ -f "${SERVER_PRIVATE_KEY}" && -f "${SERVER_PUBLIC_KEY}" ]]; then
    safe_echo "INFO" "Server keys already exist — skipping generation."
else
    safe_echo "INFO" "Generating new server key pair..."
    umask 077
    wg genkey | tee "${SERVER_PRIVATE_KEY}" | wg pubkey > "${SERVER_PUBLIC_KEY}"
    chmod 600 "${SERVER_PRIVATE_KEY}"
    chmod 644 "${SERVER_PUBLIC_KEY}"
fi

SERVER_PRIV="$(cat "${SERVER_PRIVATE_KEY}")"
SERVER_PUB="$(cat "${SERVER_PUBLIC_KEY}")"

print_section "WireGuard Configuration"

SKIP_CONFIG=false
if [[ -f "${WG_CONF}" ]]; then
    if systemctl is-active --quiet "wg-quick@${WG_INTERFACE}" 2>/dev/null && [[ "${FORCE_REGEN}" == "false" ]]; then
        safe_echo "INFO" "wg0 is active and config exists — skipping config regeneration."
        SKIP_CONFIG=true
    else
        backup_file "${WG_CONF}"
    fi
fi

if [[ "${SKIP_CONFIG}" == "false" ]]; then
    PEERS_BLOCK=""
    if [[ -f "${WG_CONF}" && "${FORCE_REGEN}" == "false" ]]; then
        PEERS_BLOCK="$(awk '/^\[Peer\]/{found=1} found{print}' "${WG_CONF}" || true)"
    fi

    cat > "${WG_CONF}" <<EOF
# RouteLag — WireGuard node config
# Generated by 01-install-node.sh

[Interface]
Address = ${SERVER_TUNNEL_IP}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIV}
SaveConfig = false

PostUp = iptables -A FORWARD -i ${WG_INTERFACE} -j ACCEPT; iptables -A FORWARD -o ${WG_INTERFACE} -j ACCEPT; iptables -t nat -A POSTROUTING -o ${DEFAULT_IFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i ${WG_INTERFACE} -j ACCEPT; iptables -D FORWARD -o ${WG_INTERFACE} -j ACCEPT; iptables -t nat -D POSTROUTING -o ${DEFAULT_IFACE} -j MASQUERADE
EOF

    if [[ -n "${PEERS_BLOCK}" ]]; then
        echo "" >> "${WG_CONF}"
        echo "${PEERS_BLOCK}" >> "${WG_CONF}"
    fi

    chmod 600 "${WG_CONF}"
fi

print_section "IP Forwarding"
cat > "${FORWARDING_CONF}" <<EOF
net.ipv4.ip_forward=1
EOF
sysctl -p "${FORWARDING_CONF}" >/dev/null

print_section "Firewall (UFW)"
ufw allow OpenSSH comment 'SSH access' >/dev/null 2>&1 || ufw allow 22/tcp comment 'SSH access'
ufw allow "${WG_PORT}/udp" comment 'WireGuard' >/dev/null 2>&1 || true

UFW_STATUS="$(ufw status 2>/dev/null | head -1 || echo 'inactive')"
if echo "${UFW_STATUS}" | grep -qi inactive; then
    ufw --force enable
fi

print_section "Starting WireGuard"
systemctl enable "wg-quick@${WG_INTERFACE}"
systemctl restart "wg-quick@${WG_INTERFACE}"
sleep 1

if ! systemctl is-active --quiet "wg-quick@${WG_INTERFACE}"; then
    journalctl -u "wg-quick@${WG_INTERFACE}" -n 20 --no-pager || true
    exit 1
fi

PUBLIC_IP="$(get_public_ip || true)"
print_section "Installation Complete"
echo ""
echo "  Server Public Key: ${SERVER_PUB}"
echo "  Endpoint:          ${PUBLIC_IP}:${WG_PORT}"
echo "  Tunnel subnet:     ${WG_SUBNET}"
echo "  Server tunnel IP:  ${SERVER_TUNNEL_IP}"
echo ""
wg show "${WG_INTERFACE}" || true
